services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  tasks:
    build:
      context: .
      dockerfile: ./tasks/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  workspaces:
    build:
      context: .
      dockerfile: ./workspaces/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  default:
    driver: bridge
