services:
  gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TASKS_SERVICE_URL=http://tasks:3002
      - WORKSPACES_SERVICE_URL=http://workspaces:3001
    depends_on:
      - tasks
      - workspaces

  tasks:
    build:
      context: .
      dockerfile: ./tasks-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  workspaces:
    build:
      context: .
      dockerfile: ./workspaces-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge
